### ISSUE TITLE
Half block/movement inconsistencies

### ISSUE THREAD

**Issue by abertell** [exit-path/game#1]
A few inconsistencies I noticed in my first few playthroughs:

Half blocks (probably hitbox related):

- When jumping into a wall above a half block and falling directly downwards, you will no longer be placed below the half block in the new version (example on Stage 2 of Uniplayer).
- You seem to be able to travel about 2 pixels further away from a ledge while crouched under a half block in the old version (see images).
![epbug](https://user-images.githubusercontent.com/59854865/100527713-ec120900-31a2-11eb-8e48-6ed8987ccdcd.png)

Movement:

- The new version lacks "leftward drifting" (for lack of a better term), where after walking to the left, the player will continue to slide by a few pixels over the span of a few seconds, even after decelerating.

**Comment by abertell** [comment]
I also just warped above the spawn area on Stage 29 during a rewind, although I have no idea how to replicate it, and am not sure if this ever happens on the old version (I've never seen it happen).

**Comment by schrislambert** [comment]
The hitdetection issues seem to come from implementation differences in the original Flash [hitTestObject()](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/DisplayObject.html#hitTestObject()) versus the one in [swf-lib](https://github.com/kiootic/swf-translator/blob/8fa9bafd01d673711064bcbee9766a0a8a288b19/packages/swf-lib/src/classes/flash/display/DisplayObject.ts#L275)

**Comment by kiootic** [comment]
> You seem to be able to travel about 2 pixels further away from a ledge while crouched under a half block in the old version (see images).

It's hard to confirm whether it's due to real logic flaws or graphical differences (which is really hard to emulate accurately).

> The new version lacks "leftward drifting" (for lack of a better term), where after walking to the left, the player will continue to slide by a few pixels over the span of a few seconds, even after decelerating.

This is caused by the two emulation issues:
- the new version is storing positions more accurately, while flash player stores in 1/20 increments (twips)
- the rounding of twips to pixel is incorrect (round instead of floor)

> When jumping into a wall above a half block and falling directly downwards, you will no longer be placed below the half block in the new version (example on Stage 2 of Uniplayer).

It's a bug in rectangle intersection logic.
