### ISSUE TITLE
swf-lib is unauthorized to download when building locally

### ISSUE THREAD

**Issue by abertell** [exit-path/game#6]
Error message when using "yarn install" from setup:
Error: https://npm.pkg.github.com/download/@kiootic/swf-lib/0.5.2/b2c844f07662f904aa3fd832fb4b6b26e9988bebb41b79024449d3e1bfee7051: Request failed "401 Unauthorized"

**Comment by kiootic** [comment]
Sorry but I'm not comfortable with putting experimental package on public npm registry, so you'll  need to login to npm with GitHub to download the package: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages
